[project]
name = "comp520"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11.8"
dependencies = [
  "beautifulsoup4>=4.13.3",
  "py-cord>=2.6.1",
  "requests>=2.32.3",
  "ruff>=0.9.4",
]
