#!/usr/bin/env bash

set -euxo pipefail

touch ~/.hushlogin

DOMAIN=$1

hostnamectl set-hostname "$DOMAIN"

apt-get install --yes \
  acl \
  clang \
  libsqlite3-dev\
  libssl-dev \
  pkg-config \
  vim

# Install `uv`
curl -LsSf https://astral.sh/uv/install.sh | sh

cp deploy/bot.service /etc/systemd/system/

systemctl daemon-reload
systemctl enable bot
systemctl restart bot

echo 'Deployed 🎉'
