#!/usr/bin/env bash

set -euxo pipefail

touch ~/.hushlogin

DOMAIN=$1
WORKING_DIR="/var/lib/bot"

hostnamectl set-hostname "$DOMAIN"

apt-get update && apt-get install --yes \
  acl \
  clang \
  libsqlite3-dev \
  libssl-dev \
  pkg-config \
  vim

# Create the `bot` user
if ! id bot &>/dev/null; then
  useradd --system --create-home --home-dir /home/bot --shell /bin/bash bot
fi

# Install `poetry`
sudo -u bot -s -- bash -c "curl -sSL https://install.python-poetry.org | python3 -"

# Copy over project
cp -r . "$WORKING_DIR"
chown -R bot:bot /var/lib/bot

# Install dependencies
sudo -u bot -s -- bash -c "cd \"$WORKING_DIR\" && /home/bot/.local/bin/poetry install"

# Start systemd service
cp deploy/bot.service /etc/systemd/system/
systemctl daemon-reload
systemctl enable bot
systemctl restart bot

echo 'Deployed 🎉'
