name: Deploy

on:
  push:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  check-workflow:
    name: Check

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Download actionlint
        id: actionlint
        run:
          bash <(curl
          https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash)

      - name: Check workflow
        run: ${{ steps.actionlint.outputs.executable }} -color

  deploy:
    name: Deploy

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Install dependencies
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            mkdir -p deploy
            sudo apt-get update --yes
            sudo apt-get upgrade --yes
            sudo apt-get install --yes git rsync
          EOF

      - name: Sync
        run: |
          rsync -avz deploy/checkout root@${{ secrets.SSH_HOST }}:deploy/checkout

      - name: Run deployment script
        run: |
          ssh root@${{ secrets.SSH_HOST }} << 'EOF'
            cd deploy && ./checkout main ${{ secrets.SSH_HOST }}
          EOF
